@startuml

actor User

participant ":MyDay\n(View/ViewModel)" as MyDay

participant ":AddEventCommand" as AddEventCommand

participant ":EventController" as EventController
participant ":HabitController" as HabitController
participant ":EventRepository" as EventRepository

User -> MyDay : Tap on incomplete card
activate MyDay

MyDay -> AddEventCommand : Create and execute command
activate AddEventCommand

AddEventCommand -> EventController : Add event
activate EventController

EventController -[dashed]-> AddEventCommand : ID of new event
deactivate EventController

AddEventCommand -> HabitController : Add event to parent habit
activate HabitController

HabitController -[dashed]-> AddEventCommand
deactivate HabitController

AddEventCommand -> EventRepository : Retrieve event based on ID
activate EventRepository

EventRepository -[dashed]-> AddEventCommand : Created event
deactivate EventRepository

AddEventCommand -[dashed]-> MyDay : Created event
destroy AddEventCommand

@enduml