@startuml

actor User

participant ":MyDay\n(View/ViewModel)" as MyDay

participant ":DeleteEventCommand" as DeleteEventCommand

participant ":HabitRepository" as HabitRepository
participant ":HabitController" as HabitController
participant ":EventController" as EventController

User -> MyDay : Tap on complete card
activate MyDay

MyDay -> DeleteEventCommand : Create and execute command
activate DeleteEventCommand

DeleteEventCommand -> HabitRepository : Find parent habit of given event
activate HabitRepository

HabitRepository -[dashed]-> DeleteEventCommand : Parent habit
deactivate HabitRepository

DeleteEventCommand -> HabitController : Detach event from parent habit
activate HabitController

HabitController -[dashed]-> DeleteEventCommand : Whether the detachment was successful
deactivate HabitController

DeleteEventCommand -> EventController : Delete event
activate EventController

EventController -[dashed]-> DeleteEventCommand : Whether the deletion was successful
deactivate EventController

DeleteEventCommand -[dashed]-> MyDay : Whether the deletion was successful
destroy DeleteEventCommand

@enduml