@startuml

actor User

participant ":MyDay\n(View/ViewModel)" as MyDay

participant ":UserRepository" as UserRepository
participant ":HabitRepository" as HabitRepository
participant ":EventRepository" as EventRepository

User -> MyDay : Navigates to
activate MyDay

MyDay -> UserRepository : Observes
activate UserRepository

MyDay -> HabitRepository : Observes
activate HabitRepository

MyDay -> EventRepository : Observes
activate EventRepository

UserRepository -[dashed]-> MyDay : Changes to the current user
HabitRepository -[dashed]-> MyDay : Changes to the habits
EventRepository -[dashed]-> MyDay : Changes to the events

@enduml